---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
implicit:
  - Сайт должен быть SPA-приложением
  - Пользователь должен иметь возможность создать аккаунт, войти и выйти из него
  - Товары в корзине должны сохраняться при обновлении страницы или повторном входе пользователя
  - Пользователь может оформить заказ с переходом на страницу оплаты
  - Фильтры должны применяться к уже найденным товарам, а не сбрасывать результаты поиска
  - На странице товара и в каталоге должно быть название, рейтинг, цена со скидкой и без нее
  - Поиск, фильтрация и загрузка страниц не должны занимать больше 2–3 секунд
  - Пароли должны храниться в зашифрованном виде; данные пользователей передаются по HTTPS
  - Сайт должен быть оптимизирован для поисковых систем
  - Интерфейс должен быть удобен для людей с ограниченными возможностями